In [4]:
import numpy as np
import pandas as pd

In [6]:
my_dict = {"James":[40,30,np.nan],"Kirk":[30,np.nan,50],"Lars":[30,50,40]}

In [8]:
my_data_frame = pd.DataFrame(my_dict)

In [10]:
my_data_frame

   James  Kirk  Lars
0   40.0  30.0    30
1   30.0   NaN    50
2    NaN  50.0    40

In [14]:
my_data_frame.dropna()
#boşluk olanları siler

   James  Kirk  Lars
0   40.0  30.0    30

In [16]:
my_data_frame

   James  Kirk  Lars
0   40.0  30.0    30
1   30.0   NaN    50
2    NaN  50.0    40

In [18]:
my_data_frame.dropna(axis=1)

   Lars
0    30
1    50
2    40

In [22]:
my_new_dict = {"James":[40,30,np.nan],"Kirk":[30,np.nan,50],"Lars":[30,50,40],"Rob":[45,np.nan,np.nan]}

In [26]:
my_new_data_frame = pd.DataFrame(my_new_dict)

In [28]:
my_new_data_frame

   James  Kirk  Lars   Rob
0   40.0  30.0    30  45.0
1   30.0   NaN    50   NaN
2    NaN  50.0    40   NaN

In [38]:
my_new_data_frame.dropna(axis=1,thresh=2) 
# thresh nan sayısına kadar sorun değil

   James  Kirk  Lars
0   40.0  30.0    30
1   30.0   NaN    50
2    NaN  50.0    40

In [42]:
my_new_data_frame.fillna(20)
# nan olanları doldur

   James  Kirk  Lars   Rob
0   40.0  30.0    30  45.0
1   30.0  20.0    50  20.0
2   20.0  50.0    40  20.0

In [44]:
# GROUP BY

In [98]:
salary_dict = {"Programming Language":["Python","Python","Python","Java","Java","Swift"],"Name":["A","B","C","D","E","F"],
"Salary":[100,90,80,70,60,50]}

In [100]:
salary_frame = pd.DataFrame(salary_dict)
salary_frame

  Programming Language Name  Salary
0               Python    A     100
1               Python    B      90
2               Python    C      80
3                 Java    D      70
4                 Java    E      60
5                Swift    F      50

In [102]:
group_object = salary_frame.groupby("Programming Language")

In [104]:
group_object["Salary"].mean()

Programming Language
Java      65.0
Python    90.0
Swift     50.0
Name: Salary, dtype: float64

In [107]:
group_object["Salary"].min()

Programming Language
Java      60
Python    80
Swift     50
Name: Salary, dtype: int64

In [109]:
group_object["Salary"].max()

Programming Language
Java       70
Python    100
Swift      50
Name: Salary, dtype: int64

In [111]:
group_object.max("Salary")

                      Salary
Programming Language
Java                      70
Python                   100
Swift                     50

In [113]:
group_object.describe()

                     Salary
                      count  mean        std   min   25%   50%   75%    max
Programming Language
Java                    2.0  65.0   7.071068  60.0  62.5  65.0  67.5   70.0
Python                  3.0  90.0  10.000000  80.0  85.0  90.0  95.0  100.0
Swift                   1.0  50.0        NaN  50.0  50.0  50.0  50.0   50.0

In [133]:
my_dict1 = {"Name":["A","B","C","D"],
           "Sports":["Bas","foot","tennis","run"],
           "Calories":[100,200,300,400]}

In [135]:
my_frame1 = pd.DataFrame(my_dict1)
my_frame1

  Name  Sports  Calories
0    A     Bas       100
1    B    foot       200
2    C  tennis       300
3    D     run       400

In [137]:
my_dict2 = {"Name":["E","F","G","H"],
           "Sports":["Bas","foot","tennis","run"],
           "Calories":[200,50,300,440]}

In [151]:
my_frame2 = pd.DataFrame(my_dict2,index=[4,5,6,7])
my_frame2

  Name  Sports  Calories
4    E     Bas       200
5    F    foot        50
6    G  tennis       300
7    H     run       440

In [141]:
my_dict3 = {"Name":["I","J","K","L"],
           "Sports":["Bas","foot","tennis","run"],
           "Calories":[300,150,320,410]}

In [155]:
my_frame3 = pd.DataFrame(my_dict3,index=[8,9,10,11])
my_frame3

   Name  Sports  Calories
8     I     Bas       300
9     J    foot       150
10    K  tennis       320
11    L     run       410

In [157]:
#concatenation

In [159]:
# data frameler  birleştirilir

In [161]:
pd.concat([my_frame1,my_frame2,my_frame3])

   Name  Sports  Calories
0     A     Bas       100
1     B    foot       200
2     C  tennis       300
3     D     run       400
4     E     Bas       200
5     F    foot        50
6     G  tennis       300
7     H     run       440
8     I     Bas       300
9     J    foot       150
10    K  tennis       320
11    L     run       410

In [163]:
#merge

In [165]:
#aynı olan verileri kullanrak iç içe geçirme

In [169]:
pd.merge(my_frame1,my_frame2,on="Sports")

  Name_x  Sports  Calories_x Name_y  Calories_y
0      A     Bas         100      E         200
1      B    foot         200      F          50
2      C  tennis         300      G         300
3      D     run         400      H         440

In [171]:
new_salary_frame = pd.DataFrame({"name":["A","B","C"],"salary":[10,20,30],"age":[60,65,70]})
new_salary_frame

  name  salary  age
0    A      10   60
1    B      20   65
2    C      30   70

In [173]:
new_salary_frame["name"].unique()

array(['A', 'B', 'C'], dtype=object)

In [175]:
new_salary_frame["name"].nunique()

3

In [177]:
def grossToNet(salary):
    return salary * 0.65

In [179]:
new_salary_frame["salary"].apply(grossToNet)

0     6.5
1    13.0
2    19.5
Name: salary, dtype: float64