In [62]:
import pandas as pd
import numpy as np

In [64]:
my_data = np.array([[10,20,30],[20,30,40],[20,50,10],[10,15,20]])
my_data

array([[10, 20, 30],
       [20, 30, 40],
       [20, 50, 10],
       [10, 15, 20]])

In [66]:
my_names = ["James","Lars","Kirk","Rob"]

In [68]:
my_columns = ["Jan","Feb","Mar"]

In [70]:
my_data_frame = pd.DataFrame(my_data)
my_data_frame

    0   1   2
0  10  20  30
1  20  30  40
2  20  50  10
3  10  15  20

In [72]:
my_data_frame[0]

0    10
1    20
2    20
3    10
Name: 0, dtype: int32

In [74]:
new_data_frame = pd.DataFrame(my_data,index=my_names,columns=my_columns)

In [76]:
new_data_frame

       Jan  Feb  Mar
James   10   20   30
Lars    20   30   40
Kirk    20   50   10
Rob     10   15   20

In [78]:
new_data_frame["Feb"]

James    20
Lars     30
Kirk     50
Rob      15
Name: Feb, dtype: int32

In [80]:
feb_series = new_data_frame["Feb"]

In [82]:
feb_series.mean()

28.75

In [84]:
feb_series.Lars

30

In [86]:
new_data_frame["Jan"].mean

<bound method Series.mean of James    10
Lars     20
Kirk     20
Rob      10
Name: Jan, dtype: int32>

In [88]:
new_data_frame.loc["Lars"]

Jan    20
Feb    30
Mar    40
Name: Lars, dtype: int32

In [90]:
new_data_frame.iloc[3]

Jan    10
Feb    15
Mar    20
Name: Rob, dtype: int32

loc → etiket (isim) kullanıyor, bitiş dahil.

iloc → indeks (pozisyon) kullanıyor, bitiş hariç.

In [93]:
new_data_frame["Apr"]=new_data_frame["Mar"]*2
new_data_frame

       Jan  Feb  Mar  Apr
James   10   20   30   60
Lars    20   30   40   80
Kirk    20   50   10   20
Rob     10   15   20   40

In [95]:
new_data_frame.drop("Rob",axis=0)

       Jan  Feb  Mar  Apr
James   10   20   30   60
Lars    20   30   40   80
Kirk    20   50   10   20

In [97]:
new_data_frame

       Jan  Feb  Mar  Apr
James   10   20   30   60
Lars    20   30   40   80
Kirk    20   50   10   20
Rob     10   15   20   40

In [99]:
new_data_frame.drop("Apr",axis=1)

       Jan  Feb  Mar
James   10   20   30
Lars    20   30   40
Kirk    20   50   10
Rob     10   15   20

In [101]:
new_data_frame.drop("Apr",axis=1 , inplace=True) #inplace kalıcı olmasını sağlar

In [103]:
new_data_frame

       Jan  Feb  Mar
James   10   20   30
Lars    20   30   40
Kirk    20   50   10
Rob     10   15   20

In [105]:
new_data_frame

       Jan  Feb  Mar
James   10   20   30
Lars    20   30   40
Kirk    20   50   10
Rob     10   15   20

In [107]:
new_data_frame["Jan"]["Lars"]

20

In [114]:
boolean_frame = new_data_frame>25
boolean_frame

         Jan    Feb    Mar
James  False  False   True
Lars   False   True   True
Kirk   False   True  False
Rob    False  False  False

In [116]:
new_data_frame[boolean_frame]

       Jan   Feb   Mar
James  NaN   NaN  30.0
Lars   NaN  30.0  40.0
Kirk   NaN  50.0   NaN
Rob    NaN   NaN   NaN

In [118]:
new_data_frame[new_data_frame>30]

       Jan   Feb   Mar
James  NaN   NaN   NaN
Lars   NaN   NaN  40.0
Kirk   NaN  50.0   NaN
Rob    NaN   NaN   NaN

In [120]:
new_data_frame[new_data_frame["Mar"]>25]

       Jan  Feb  Mar
James   10   20   30
Lars    20   30   40

In [122]:
new_data_frame.reset_index()

   index  Jan  Feb  Mar
0  James   10   20   30
1   Lars   20   30   40
2   Kirk   20   50   10
3    Rob   10   15   20

In [124]:
new_data_frame["NewIndex"]=["Jam","Lar","Kir","Robert"]

In [126]:
new_data_frame

       Jan  Feb  Mar NewIndex
James   10   20   30      Jam
Lars    20   30   40      Lar
Kirk    20   50   10      Kir
Rob     10   15   20   Robert

In [128]:
new_data_frame.set_index("NewIndex")

          Jan  Feb  Mar
NewIndex
Jam        10   20   30
Lar        20   30   40
Kir        20   50   10
Robert     10   15   20

In [130]:
new_data_frame.drop("NewIndex",axis=1,inplace=True)

In [132]:
new_data_frame

       Jan  Feb  Mar
James   10   20   30
Lars    20   30   40
Kirk    20   50   10
Rob     10   15   20